{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2010e349",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np \n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import igraph as ig\n",
    "from io import StringIO\n",
    "import glob\n",
    "import os\n",
    "from helper_functions import *\n",
    "from extract_data_pipeline import *\n",
    "from extract_data_pipeline_no_topology import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "5c93ed01",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1969-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1970-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1971-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1972-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1973-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1974-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1975-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1976-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1977-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1978-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1979-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1980-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1981-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1982-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1983-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1984-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1985-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1986-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1987-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1988-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1989-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1990-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1991-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1992-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1993-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1994-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1995-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1996-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1997-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1998-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-1999-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2000-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2001-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2002-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2003-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2004-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2005-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2006-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2007-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2008-adjacency-number.txt\n",
      "Processing: ./mexicodf/Mexico-topologies/Mexico-2009-adjacency-number.txt\n",
      "./mexicodf/mxline*.txt\n",
      "Processing: ./mexicodf/mxline1.txt\n",
      "Processing: ./mexicodf/mxline12.txt\n",
      "Processing: ./mexicodf/mxline2.txt\n",
      "Processing: ./mexicodf/mxline3.txt\n",
      "Processing: ./mexicodf/mxline4.txt\n",
      "Processing: ./mexicodf/mxline5.txt\n",
      "Processing: ./mexicodf/mxline6.txt\n",
      "Processing: ./mexicodf/mxline7.txt\n",
      "Processing: ./mexicodf/mxline8.txt\n",
      "Processing: ./mexicodf/mxline9.txt\n",
      "Processing: ./mexicodf/mxlineA.txt\n",
      "Processing: ./mexicodf/mxlineB.txt\n",
      "Unmatched station: 20deNoviembre\n",
      "Unmatched station: 20deNoviembre\n",
      "Unmatched station: ParquedelosVenados\n",
      "Unmatched station: ParquedelosVenados\n",
      "Unmatched station: EjeCentral\n",
      "Unmatched station: EjeCentral\n",
      "Unmatched station: Mexicaltzingo\n",
      "Unmatched station: Mexicaltzingo\n",
      "Unmatched station: PuebloCulhuacan\n",
      "Unmatched station: PuebloCulhuacan\n",
      "Unmatched station: ESIMECulhuacan\n",
      "Unmatched station: ESIMECulhuacan\n",
      "Unmatched station: Tornatlan\n",
      "Unmatched station: Tornatlan\n",
      "Unmatched station: Calle11\n",
      "Unmatched station: Calle11\n",
      "Unmatched station: PerifericoOte\n",
      "Unmatched station: PerifericoOte\n",
      "Unmatched station: Tezonco\n",
      "Unmatched station: Tezonco\n",
      "Unmatched station: Olivos\n",
      "Unmatched station: Olivos\n",
      "Unmatched station: Nopalera\n",
      "Unmatched station: Nopalera\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline2']\n",
      "['mxline1']\n",
      "['mxline1']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline1']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline5']\n",
      "['mxline5']\n",
      "['mxline5']\n",
      "['mxline5']\n",
      "['mxline5']\n",
      "['mxline4']\n",
      "['mxline4']\n",
      "['mxline4']\n",
      "['mxline4']\n",
      "['mxline5']\n",
      "['mxline4']\n",
      "['mxline4']\n",
      "['mxline4']\n",
      "['mxline5']\n",
      "['mxline5']\n",
      "['mxline5']\n",
      "['mxline5']\n",
      "['mxline5']\n",
      "['mxline5']\n",
      "['mxline4']\n",
      "['mxline4']\n",
      "['mxline3']\n",
      "['mxline6']\n",
      "['mxline6']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline6']\n",
      "['mxline6']\n",
      "['mxline6']\n",
      "['mxline3']\n",
      "['mxline3']\n",
      "['mxline2']\n",
      "['mxline2']\n",
      "['mxline7']\n",
      "['mxline7']\n",
      "['mxline7']\n",
      "['mxline1']\n",
      "['mxline7']\n",
      "['mxline7']\n",
      "['mxline7']\n",
      "['mxline7']\n",
      "['mxline7']\n",
      "['mxline7']\n",
      "['mxline6']\n",
      "['mxline6']\n",
      "['mxline6']\n",
      "['mxline6']\n",
      "['mxline9']\n",
      "['mxline9']\n",
      "['mxline9']\n",
      "['mxline9']\n",
      "['mxline9']\n",
      "['mxline9']\n",
      "['mxline9']\n",
      "['mxline9']\n",
      "['mxline7']\n",
      "['mxline7']\n",
      "['mxline9']\n",
      "['mxline9']\n",
      "['mxline7']\n",
      "['mxline6']\n",
      "['mxline7']\n",
      "['mxline9']\n",
      "['mxlineA']\n",
      "['mxlineA']\n",
      "['mxlineA']\n",
      "['mxlineA']\n",
      "['mxlineA']\n",
      "['mxlineA']\n",
      "['mxlineA']\n",
      "['mxlineA']\n",
      "['mxlineA']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxline8']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "['mxlineB']\n",
      "before reset id (164, 6)\n",
      "after reset id (164, 4)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/william/complex_networks/projects/data_project/helper_functions.py:340: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  stations_grouped[0] = stations_grouped[0][stations_grouped[0] != 'Roosevel']\n",
      "/home/william/complex_networks/projects/data_project/helper_functions.py:340: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`\n",
      "  stations_grouped[0] = stations_grouped[0][stations_grouped[0] != 'Roosevel']\n"
     ]
    }
   ],
   "source": [
    "file_pattern_topologies = \"./mexicodf/Mexico-topologies/Mexico-*-adjacency-number.txt\"\n",
    "file_lines = None\n",
    "line_prefixes = [\"mxline\"]\n",
    "filename_nodes = \"./mexicodf/mexico-positions-years.txt\"\n",
    "\n",
    "city_path = \"./mexicodf\"\n",
    "file_prefix = \"\"\n",
    "file_suffix = \".txt\"\n",
    "\n",
    "output_edges = \"Mexico_edgelist.csv\"\n",
    "output_nodes = \"Mexico_nodelist.csv\"\n",
    "\n",
    "extract_data_pipeline_no_topology(file_pattern_topologies, file_lines, filename_nodes, output_edges, output_nodes, city_path = city_path, \n",
    "                      file_prefix = file_prefix, file_suffix = file_suffix,  line_prefixes=line_prefixes, more_files = True, separator = False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "python3_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
