{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ec37b6e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np \n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import igraph as ig\n",
    "from io import StringIO\n",
    "import glob\n",
    "import os\n",
    "from helper_functions import *\n",
    "from extract_data_pipeline import *\n",
    "from extract_data_pipeline_no_topology import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "57780fe9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1919-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1920-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1921-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1922-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1923-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1924-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1925-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1926-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1927-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1928-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1929-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1930-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1931-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1932-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1933-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1934-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1935-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1936-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1937-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1938-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1939-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1940-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1941-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1942-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1943-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1944-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1945-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1946-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1947-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1948-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1949-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1950-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1951-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1952-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1953-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1954-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1955-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1956-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1957-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1958-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1959-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1960-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1961-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1962-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1963-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1964-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1965-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1966-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1967-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1968-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1969-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1970-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1971-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1972-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1973-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1974-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1975-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1976-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1977-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1978-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1979-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1980-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1981-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1982-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1983-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1984-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1985-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1986-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1987-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1988-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1989-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1990-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1991-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1992-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1993-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1994-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1995-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1996-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1997-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1998-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-1999-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2000-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2001-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2002-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2003-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2004-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2005-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2006-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2007-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2008-adjacency-number.txt\n",
      "Processing: ./Madrid/madrid-topologies-noLR/Madrid-2009-adjacency-number.txt\n",
      "./Madrid/madrid-line*.txt\n",
      "./Madrid/madrid-ramal*.txt\n",
      "Processing: ./Madrid/madrid-line1.txt\n",
      "Processing: ./Madrid/madrid-line10.txt\n",
      "Processing: ./Madrid/madrid-line11.txt\n",
      "Processing: ./Madrid/madrid-line12.txt\n",
      "Processing: ./Madrid/madrid-line2.txt\n",
      "Processing: ./Madrid/madrid-line3.txt\n",
      "Processing: ./Madrid/madrid-line4.txt\n",
      "Processing: ./Madrid/madrid-line5.txt\n",
      "Processing: ./Madrid/madrid-line6.txt\n",
      "Processing: ./Madrid/madrid-line7.txt\n",
      "Processing: ./Madrid/madrid-line8.txt\n",
      "Processing: ./Madrid/madrid-line9.txt\n",
      "Processing: ./Madrid/madrid-lineml1.txt\n",
      "Processing: ./Madrid/madrid-lineml2.txt\n",
      "Processing: ./Madrid/madrid-lineml3.txt\n",
      "Processing: ./Madrid/madrid-ramal.txt\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "[]\n",
      "['line2']\n",
      "['line2']\n",
      "[]\n",
      "['line2']\n",
      "['line2']\n",
      "['line2']\n",
      "[]\n",
      "['line2']\n",
      "[]\n",
      "['line2']\n",
      "['line2']\n",
      "['line2']\n",
      "[]\n",
      "['line2']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line4']\n",
      "[]\n",
      "['line3']\n",
      "[]\n",
      "[]\n",
      "['line3']\n",
      "['line3']\n",
      "[]\n",
      "['line5']\n",
      "['line5']\n",
      "[]\n",
      "['line5']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line3']\n",
      "['line3']\n",
      "['line3']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "['line3']\n",
      "['line5']\n",
      "['line5']\n",
      "[]\n",
      "[]\n",
      "['line6']\n",
      "['line6']\n",
      "[]\n",
      "['line6']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line6']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line5']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line4']\n",
      "['line4']\n",
      "[]\n",
      "['line9']\n",
      "['line9']\n",
      "['line9']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line9']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line7']\n",
      "['line7']\n",
      "['line7']\n",
      "['line4', 'line6']\n",
      "['line4']\n",
      "[]\n",
      "['line4']\n",
      "[]\n",
      "[]\n",
      "['line11']\n",
      "['line10']\n",
      "[]\n",
      "['line5']\n",
      "[]\n",
      "['line7']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line10']\n",
      "[]\n",
      "['line10']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line10']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line7']\n",
      "[]\n",
      "[]\n",
      "['lineml1']\n",
      "['line1', 'line10']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line12']\n",
      "[]\n",
      "['line12']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line7']\n",
      "['line7']\n",
      "[]\n",
      "['line1']\n",
      "['line1']\n",
      "['line1']\n",
      "[]\n",
      "[]\n",
      "['line6']\n",
      "[]\n",
      "['line7']\n",
      "['line7']\n",
      "[]\n",
      "['line11']\n",
      "['line11']\n",
      "[]\n",
      "[]\n",
      "['line9']\n",
      "[]\n",
      "['line11']\n",
      "['line8']\n",
      "[]\n",
      "['line4']\n",
      "['line4']\n",
      "[]\n",
      "[]\n",
      "['line4']\n",
      "['line4']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['lineml2']\n",
      "[]\n",
      "[]\n",
      "['line6']\n",
      "['line8']\n",
      "['line1']\n",
      "['line7']\n",
      "['line1']\n",
      "['line7']\n",
      "['line10']\n",
      "[]\n",
      "['line1']\n",
      "['line10']\n",
      "['line8']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['line10']\n",
      "[]\n",
      "[]\n",
      "['line6']\n",
      "['line6']\n",
      "[]\n",
      "['lineml1']\n",
      "['lineml1']\n",
      "[]\n",
      "['lineml1']\n",
      "['line5']\n",
      "['lineml2']\n",
      "[]\n",
      "['lineml2']\n",
      "['lineml2']\n",
      "['line3']\n",
      "['line3']\n",
      "['line12']\n",
      "['line12']\n",
      "['line12']\n",
      "['line9']\n",
      "['line1']\n",
      "['line1']\n",
      "['line9']\n",
      "['line9']\n",
      "['line12']\n",
      "['line12']\n",
      "['line12']\n",
      "['line12']\n",
      "['line12']\n",
      "['line12']\n",
      "[]\n",
      "['line12']\n",
      "['line1']\n",
      "['line4']\n",
      "['line4']\n",
      "[]\n",
      "['line3']\n",
      "['line9']\n",
      "['line9']\n",
      "['line1']\n",
      "['line1']\n",
      "['line12']\n",
      "['line9']\n",
      "[]\n",
      "['line4']\n",
      "['line3']\n",
      "['line3', 'line6']\n",
      "['line4']\n",
      "['line9']\n",
      "['line9']\n",
      "['line12']\n",
      "['line12']\n",
      "['line12']\n",
      "['line12']\n",
      "['line12']\n",
      "before reset id (250, 6)\n",
      "after reset id (250, 4)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/william/complex_networks/projects/data_project/helper_functions.py:340: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  stations_grouped[0] = stations_grouped[0][stations_grouped[0] != 'Roosevel']\n",
      "/home/william/complex_networks/projects/data_project/helper_functions.py:340: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`\n",
      "  stations_grouped[0] = stations_grouped[0][stations_grouped[0] != 'Roosevel']\n"
     ]
    }
   ],
   "source": [
    "file_pattern_topologies = \"./Madrid/madrid-topologies-noLR/Madrid-*-adjacency-number.txt\"\n",
    "file_lines = None\n",
    "line_prefixes = [\"line\",\"ramal\"]\n",
    "filename_nodes = \"./Madrid/madrid-stations-times.txt\"\n",
    "\n",
    "city_path = \"./Madrid\"\n",
    "file_prefix = \"madrid-\"\n",
    "file_suffix = \".txt\"\n",
    "\n",
    "output_edges = \"Madrid_edgelist.csv\"\n",
    "output_nodes = \"Madrid_nodelist.csv\"\n",
    "\n",
    "extract_data_pipeline_no_topology(file_pattern_topologies, file_lines, filename_nodes, output_edges, output_nodes, city_path = city_path, \n",
    "                      file_prefix = file_prefix, file_suffix = file_suffix,  line_prefixes=line_prefixes, more_files = True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "python3_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
