{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7036ba18",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np \n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import igraph as ig\n",
    "from io import StringIO\n",
    "import glob\n",
    "import os\n",
    "from helper_functions import *\n",
    "from extract_data_pipeline import *\n",
    "from extract_data_pipeline_no_topology import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "13dec7c8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing: ./london-tube/London-topologies/London-1863-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1864-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1865-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1866-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1867-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1868-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1869-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1870-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1871-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1872-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1873-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1874-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1875-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1876-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1877-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1878-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1879-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1880-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1881-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1882-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1883-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1884-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1885-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1886-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1887-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1888-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1889-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1890-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1891-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1892-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1893-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1894-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1895-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1896-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1897-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1898-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1899-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1900-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1901-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1902-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1903-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1904-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1905-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1906-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1907-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1908-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1909-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1910-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1911-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1912-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1913-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1914-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1915-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1916-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1917-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1918-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1919-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1920-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1921-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1922-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1923-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1924-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1925-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1926-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1927-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1928-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1929-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1930-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1931-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1932-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1933-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1934-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1935-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1936-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1937-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1938-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1939-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1940-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1941-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1942-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1943-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1944-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1945-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1946-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1947-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1948-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1949-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1950-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1951-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1952-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1953-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1954-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1955-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1956-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1957-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1958-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1959-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1960-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1961-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1962-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1963-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1964-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1965-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1966-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1967-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1968-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1969-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1970-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1971-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1972-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1973-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1974-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1975-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1976-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1977-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1978-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1979-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1980-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1981-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1982-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1983-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1984-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1985-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1986-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1987-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1988-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1989-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1990-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1991-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1992-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1993-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1994-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1995-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1996-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1997-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1998-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-1999-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2000-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2001-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2002-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2003-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2004-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2005-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2006-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2007-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2008-adjacency-number.txt\n",
      "Processing: ./london-tube/London-topologies/London-2009-adjacency-number.txt\n",
      "./london-tube/tube-bakerloo*.txt\n",
      "./london-tube/tube-central*.txt\n",
      "./london-tube/tube-circle*.txt\n",
      "./london-tube/tube-district*.txt\n",
      "./london-tube/tube-hammersmith*.txt\n",
      "./london-tube/tube-jubilee*.txt\n",
      "./london-tube/tube-metropolitan*.txt\n",
      "./london-tube/tube-northern*.txt\n",
      "./london-tube/tube-piccadilly*.txt\n",
      "./london-tube/tube-victoria*.txt\n",
      "./london-tube/tube-waterloo*.txt\n",
      "Processing: ./london-tube/tube-bakerloo.txt\n",
      "Processing: ./london-tube/tube-central.txt\n",
      "Processing: ./london-tube/tube-circle.txt\n",
      "Processing: ./london-tube/tube-district.txt\n",
      "Processing: ./london-tube/tube-hammersmith.txt\n",
      "Processing: ./london-tube/tube-jubilee.txt\n",
      "Processing: ./london-tube/tube-metropolitan.txt\n",
      "Processing: ./london-tube/tube-northern.txt\n",
      "Processing: ./london-tube/tube-piccadilly.txt\n",
      "Processing: ./london-tube/tube-victoria.txt\n",
      "Processing: ./london-tube/tube-waterloo.txt\n",
      "['circle', 'hammersmith', 'metropolitan']\n",
      "['circle', 'hammersmith', 'metropolitan']\n",
      "['circle', 'hammersmith', 'metropolitan']\n",
      "['circle', 'hammersmith', 'metropolitan']\n",
      "[]\n",
      "['bakerloo', 'circle', 'hammersmith']\n",
      "[]\n",
      "['circle', 'hammersmith']\n",
      "['circle', 'hammersmith', 'metropolitan']\n",
      "['circle', 'hammersmith', 'metropolitan']\n",
      "['hammersmith']\n",
      "[]\n",
      "[]\n",
      "['circle']\n",
      "[]\n",
      "['circle', 'district', 'piccadilly']\n",
      "['circle', 'district']\n",
      "['circle', 'district']\n",
      "['circle', 'district']\n",
      "['circle', 'district']\n",
      "['hammersmith']\n",
      "[]\n",
      "['circle', 'district']\n",
      "['circle', 'district']\n",
      "['circle', 'district']\n",
      "['district', 'piccadilly']\n",
      "['hammersmith']\n",
      "['hammersmith']\n",
      "['district']\n",
      "['circle', 'district']\n",
      "['district']\n",
      "['district']\n",
      "['district']\n",
      "['circle', 'hammersmith', 'metropolitan']\n",
      "['circle', 'metropolitan']\n",
      "['district']\n",
      "[]\n",
      "['district']\n",
      "['district']\n",
      "[]\n",
      "['district']\n",
      "['district']\n",
      "['district', 'piccadilly']\n",
      "['metropolitan']\n",
      "['district']\n",
      "['district']\n",
      "['district']\n",
      "['district']\n",
      "[]\n",
      "[]\n",
      "['hammersmith']\n",
      "['circle']\n",
      "['circle']\n",
      "['district', 'hammersmith']\n",
      "['circle']\n",
      "['district']\n",
      "['circle', 'district']\n",
      "['circle', 'district']\n",
      "['circle']\n",
      "['circle', 'district']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['district']\n",
      "['district']\n",
      "['district']\n",
      "['district']\n",
      "['metropolitan']\n",
      "['metropolitan']\n",
      "['metropolitan']\n",
      "['northern']\n",
      "[]\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "[]\n",
      "[]\n",
      "['metropolitan']\n",
      "['metropolitan']\n",
      "[]\n",
      "[]\n",
      "['northern']\n",
      "[]\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "[]\n",
      "[]\n",
      "['central']\n",
      "[]\n",
      "['central']\n",
      "[]\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['district', 'hammersmith']\n",
      "[]\n",
      "['district', 'hammersmith']\n",
      "['district', 'hammersmith']\n",
      "['district', 'hammersmith']\n",
      "['district', 'hammersmith']\n",
      "['district', 'hammersmith']\n",
      "['district', 'hammersmith']\n",
      "['district', 'hammersmith']\n",
      "[]\n",
      "[]\n",
      "['district', 'hammersmith']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['metropolitan', 'piccadilly']\n",
      "[]\n",
      "['district']\n",
      "['district']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['northern']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['waterloo']\n",
      "['bakerloo', 'northern']\n",
      "['bakerloo']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['central']\n",
      "['northern']\n",
      "[]\n",
      "['piccadilly']\n",
      "['northern']\n",
      "['piccadilly']\n",
      "[]\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['bakerloo']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['bakerloo', 'northern']\n",
      "['bakerloo']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "[]\n",
      "['bakerloo']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['metropolitan', 'piccadilly']\n",
      "[]\n",
      "['central']\n",
      "['piccadilly']\n",
      "[]\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "['northern', 'victoria']\n",
      "['piccadilly']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern', 'victoria']\n",
      "['northern']\n",
      "['northern']\n",
      "['piccadilly']\n",
      "['northern']\n",
      "['northern']\n",
      "[]\n",
      "['metropolitan']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['metropolitan']\n",
      "['metropolitan']\n",
      "['district']\n",
      "['district']\n",
      "['metropolitan', 'piccadilly']\n",
      "['metropolitan', 'piccadilly']\n",
      "['metropolitan']\n",
      "['metropolitan']\n",
      "['hammersmith']\n",
      "['hammersmith']\n",
      "['bakerloo']\n",
      "[]\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "['metropolitan']\n",
      "['metropolitan']\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "[]\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "[]\n",
      "[]\n",
      "['northern']\n",
      "['northern']\n",
      "['metropolitan', 'piccadilly']\n",
      "['metropolitan']\n",
      "['central']\n",
      "['metropolitan']\n",
      "['central']\n",
      "['central']\n",
      "['metropolitan', 'piccadilly']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['metropolitan']\n",
      "['metropolitan']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['district']\n",
      "['district']\n",
      "['district']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['district']\n",
      "['piccadilly']\n",
      "['bakerloo']\n",
      "['bakerloo']\n",
      "['metropolitan']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['metropolitan']\n",
      "['district']\n",
      "['district']\n",
      "['district']\n",
      "['district']\n",
      "[]\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['northern']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "[]\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "['central']\n",
      "[]\n",
      "['victoria']\n",
      "['victoria']\n",
      "['victoria']\n",
      "['victoria']\n",
      "['victoria']\n",
      "['victoria']\n",
      "['victoria']\n",
      "['victoria']\n",
      "['victoria']\n",
      "['victoria']\n",
      "['victoria']\n",
      "[]\n",
      "['victoria']\n",
      "['victoria']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "[]\n",
      "['jubilee']\n",
      "[]\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['piccadilly']\n",
      "['piccadilly']\n",
      "[]\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['jubilee']\n",
      "['piccadilly']\n",
      "['hammersmith']\n",
      "['hammersmith']\n",
      "before reset id (408, 6)\n",
      "after reset id (408, 4)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/william/complex_networks/projects/data_project/helper_functions.py:340: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  stations_grouped[0] = stations_grouped[0][stations_grouped[0] != 'Roosevel']\n",
      "/home/william/complex_networks/projects/data_project/helper_functions.py:340: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`\n",
      "  stations_grouped[0] = stations_grouped[0][stations_grouped[0] != 'Roosevel']\n"
     ]
    }
   ],
   "source": [
    "file_pattern_topologies = \"./london-tube/London-topologies/London-*-adjacency-number.txt\"\n",
    "file_lines = None\n",
    "line_prefixes = [\"bakerloo\",\"central\",\"circle\",\"district\",\"hammersmith\",\"jubilee\",\"metropolitan\",\n",
    "                 \"northern\",\"piccadilly\",\"victoria\",\"waterloo\"]\n",
    "filename_nodes = \"./london-tube/tube-stations-positions-years.txt\"\n",
    "\n",
    "city_path = \"./london-tube\"\n",
    "file_prefix = \"tube-\"\n",
    "file_suffix = \".txt\"\n",
    "\n",
    "output_edges = \"London_edgelist.csv\"\n",
    "output_nodes = \"London_nodelist.csv\"\n",
    "\n",
    "extract_data_pipeline_no_topology(file_pattern_topologies, file_lines, filename_nodes, output_edges, output_nodes, city_path = city_path, \n",
    "                      file_prefix = file_prefix, file_suffix = file_suffix,  line_prefixes=line_prefixes, more_files = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "26805bd7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "python3_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
